environment             = "dev"
project_name            = "myproj"
resource_group_name     = "rg-myproj-dev"
location                = "eastus"
vm_count                = 2
vmss_instance_count     = 3
vm_size                 = "Standard_DS1_v2"
mysql_sku               = "GP_Gen5_2"
subscription_id         = ""  # Set via environment variable ARM_SUBSCRIPTION_ID
client_id               = ""  # Set via environment variable ARM_CLIENT_ID
client_secret           = ""  # Set via environment variable ARM_CLIENT_SECRET
tenant_id               = ""  # Set via environment variable ARM_TENANT_ID
